name = "trpfrog-diffusion"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]
routes = [
  { pattern = "api.trpfrog.net/icongen", zone_name = "trpfrog.net" },
  { pattern = "api.trpfrog.net/icongen/*", zone_name = "trpfrog.net" }
]

[observability]
enabled = true

[[kv_namespaces]]
binding = "DIFFUSION_KV"
id = "17627d198edc43588fcd79b65b239e55"
